export const TYPE_COLOR = {
    normal: "grey",
    fire: "coral",
    fighting: "firebrick",
    water: "blue",
    flying: "mediumpurple",
    grass: "green",
    poison: "purple",
    electric: "yellow",
    ground: "khaki",
    psychic: "hotpink",
    rock: "tan",
    ice: "powderblue",
    bug: "yellowgreen",
    dragon: "darkslateblue",
    ghost: "rgb(106,90,205)",
    dark: "dimgray",
    steel: "lightgray",
    fairy: "pink",
  };