export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS'
export const FETCH_POKEMON_FAILED = 'FETCH_POKEMON_FAILED'
export const FETCH_POKEMON_BY_ID_SUCCESS = 'FETCH_POKEMON_BY_ID_SUCCESS'
export const FETCH_POKEMON_BY_ID_FAILED = 'FETCH_POKEMON_BY_ID_FAILED'