export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS'
export const FETCH_POKEMON_FAILED = 'FETCH_POKEMON_FAILED'
export const FETCH_POKEMON_BY_ID_SUCCESS = 'FETCH_POKEMON_BY_ID_SUCCESS'
export const FETCH_POKEMON_BY_ID_FAILED = 'FETCH_POKEMON_BY_ID_FAILED'
export const FETCH_POKEMON_BY_ID = 'FETCH_POKEMON_BY_ID'
export const FETCH_POKEMON_BY_USER_FAVORITE = 'FETCH_POKEMON_BY_ID'
export const FETCH_POKEMON_LIST = 'FETCH_POKEMON_LIST'
export const ADD_POKEMON_TO_STATE = 'ADD_POKEMON_TO_STATE'
export const ADD_POKEMON_USER_FAVORITE = 'ADD_POKEMON_USER_FAVORITE'
export const REMOVE_POKEMON_USER_FAVORITE = 'REMOVE_POKEMON_USER_FAVORITE'
export const REMOVE_POKEMON_FROM_STATE = 'REMOVE_POKEMON_FROM_STATE'
export const GET_USER_FAVORITE_POKEMON_SUCCESS = 'GET_USER_FAVORITE_POKEMON_SUCCESS'
export const GET_USER_FAVORITE_POKEMON_FAILED = 'GET_USER_FAVORITE_POKEMON_FAILED'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT'
export const AUTH_USER_SIGNUP = 'AUTH_USER_SIGNUP'
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT'
export const AUTH_GET_USER_CREDENTIALS = 'AUTH_GET_USER_CREDENTIALS'
export const AUTH_SET_REDIRECT_PATH = 'AUTH_SET_REDIRECT_PATH'
export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER'
export const AUTH_RESET_ERROR = 'AUTH_RESET_ERROR'



export const SET_USER_INFORMATION = 'SET_USER_INFORMATION'


