# Generated by Django 3.0.4 on 2020-04-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pokemon_userfavoritepokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='idNumber',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.RemoveField(
            model_name='userfavoritepokemon',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='userfavoritepokemon',
            name='pokemon',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Pokemon'),
        ),
    ]
