# Generated by Django 3.0.4 on 2020-04-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200404_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='idNum',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='userfavoritepokemon',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='userfavoritepokemon',
            name='pokemon',
            field=models.ManyToManyField(to='users.Pokemon'),
        ),
    ]
