# Generated by Django 3.0.4 on 2020-04-06 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200404_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavoritepokemon',
            name='id',
        ),
        migrations.AlterField(
            model_name='userfavoritepokemon',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
